### ISSUE TITLE
Error since upgrading to beta8

### ISSUE THREAD

**Issue by bonejon** [pubnub/pubnub-angular2#12]
Hi,

We are using angular2 with systemjs, our package.json entries are as follows:
   "pubnub": "^4.3.3",
    "pubnub-angular2": "^1.0.0-beta.7",
 
Since the publish of 1.0.0-beta-8 yesterday we get the following error:

            TypeError: ctorParameters.map is not a function
            at ReflectionCapabilities.parameters (http://localhost:9876/node_modules/@angular/core/bundles/core.umd.js:2118:51)
            at Reflector.parameters (http://localhost:9876/node_modules/@angular/core/bundles/core.umd.js:2319:52)
            at CompileMetadataResolver.getDependenciesMetadata (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14336:81)
            at CompileMetadataResolver.getTypeMetadata (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14301:28)
            at CompileMetadataResolver.getDirectiveMetadata (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14074:30)
            at eval (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14143:51)
            at Array.forEach (native)
            at CompileMetadataResolver.getNgModuleMetadata (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14136:46)
            at eval (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:52)
            at Array.forEach (native)
            at CompileMetadataResolver.getNgModuleMetadata (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
            at RuntimeCompiler._compileComponents (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:16803:49)
            at RuntimeCompiler._compileModuleAndAllComponents (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:16747:39)
            at RuntimeCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler.umd.js:16735:23)
            at TestingCompilerImpl.compileModuleAndAllComponentsSync (http://localhost:9876/node_modules/@angular/compiler/bundles/compiler-testing.umd.js:758:35)
            at TestBed._initIfNeeded (http://localhost:9876/node_modules/@angular/core/bundles/core-testing.umd.js:1059:40)
            at TestBed.execute (http://localhost:9876/node_modules/@angular/core/bundles/core-testing.umd.js:1119:18)
            at eval (http://localhost:9876/node_modules/@angular/core/bundles/core-testing.umd.js:1211:49)
            at Object.eval (http://localhost:9876/node_modules/@angular/core/bundles/core-testing.umd.js:428:30)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:203:28)at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:72:39)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:202:34)
            at Zone.run (node_modules/zone.js/dist/zone.js:96:43)
            at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:91:50)
            at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/jasmine-patch.js:119:42)
            at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:236:37)
            at Zone.runTask (node_modules/zone.js/dist/zone.js:136:47)
            at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:368:35)

The stack trace is from running unit tests, but the same error can be seen in the browser console when running the application.

I would appreciate any assistance.

**Comment by bonejon** [comment]
I may have jumped the gun. I've reverted the changes to the pubnub components and the error has come back.

Please feel free to close this issue, and I'll reopen if necessary.

**Comment by MaxPresman** [comment]
@bonejon sounds good, please let us know if we can help with anything by opening an issue or emailing `support@pubnub.com`
