### ISSUE TITLE
Reconnection event error

### ISSUE THREAD

**Issue by fsalomon** [pubnub/pubnub-angular2#15]
I get this error with pubnub-angular2 v1.0.0 and pubnub v4.4.4 every time I reconnect my network.

<pre>TypeError: Cannot read property 'forEach' of undefined
    at Object.self.listener.(anonymous function) [as status] (http://localhost:8100/build/main.js:110124:40)
    at http://localhost:8100/pubnub.js:3745:45
    at Array.forEach (native)
    at _class.announceStatus (http://localhost:8100/pubnub.js:3744:29)
    at _class.announceNetworkUp (http://localhost:8100/pubnub.js:3760:18)
    at _class.__networkUpDetected (http://localhost:8100/pubnub.js:398:35)
    at http://localhost:8100/pubnub.js:120:19
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:36872:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)</pre>

I reduced my setup to a single PubNubAngular.init() call.

**Comment by ManuelFernando** [comment]
@fsalomon this issue is really to associated to pubnub javascript sdk, thanks for reporting this. We are going to check it, ca you tell us how is the process to reconnect to your network

**Comment by fsalomon** [comment]
I'm using Ubuntu 16.04. I just disconnect and reconnect to the network using the network-manager applet. Actually, I'm getting the the same error on disconnect.

**Comment by ManuelFernando** [comment]
@fsalomon we could reproduce your scenario, thanks for reporting this. A quick question after appearing this issue can you publish and receive messages despite appearing this issue in our case the sdk continues to working.

**Comment by fsalomon** [comment]
Yes, subscriptions still work, i.e. message events are still fired.
